### PR TITLE
Update openvp configurations to not depend on old, decommissioned vc-authn

### PR DESCRIPTION
**Pull request by esune**
The API pod requires a JWKS uri parameter to be set even if it doesn't actually check for tokens. Piggybacking off the `digitaltrust-citz` Keycloak realms for this - previously the service was piggybacking the old vc-authn instance, which has now been decommissioned.

Changes manually applied/tested in `dev`, need to be deployed to `test` and `prod`.

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Looks like the same updates need to be made to the CANdy issuers.

**Comment by WadeBarnes** [comment]
~After scaling down the old `vc-authn` instances, issuing from test is not working.  It hangs after making the initial connection with the wallet. https://openvp-rev-issuer-test.apps.silver.devops.gov.bc.ca/~

Helps if I read the comment fully "**need to** be deployed to `test` and `prod`."

**Comment by WadeBarnes** [comment]
Pulling the changes and will continue the deployment and testing.

**Comment by WadeBarnes** [comment]
The configurations have been updated, deployed, and tested in `dev`, `test`, and `prod`.  Issues discovered with the `openvp-rev` instance configuration have been rectified and the unused config maps have been cleaned up.  The old `vc-authn` instances have all been scaled down to wait out the typical scream test period before being fully decommissioned.

The configurations include the workaround for `issuer-web` instances described here; https://github.com/bcgov/issuer-kit/issues/441

**Review by WadeBarnes — APPROVED** [review]

**Comment by WadeBarnes** [comment]
@esune, I'll let you review before merging.

**Review by esune — COMMENTED** [review]
Can't approve as I started the PR and am therefore an author, but this looks good to me. Thanks @WadeBarnes !

**Pull request merged**
